### ISSUE TITLE
New backend config relies on undefined var

### ISSUE THREAD

**Issue by mikelococo** [mrlesmithjr/ansible-netdata#10]
The recently added backend configs fail the ansible run even when netdata_configure_archive because there is no default value for `{{ vip }}`. Maybe default it to 127.0.0.1 just to give it a value?

```
fatal: [hostname]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: {{ vip }}:5252: 'vip' is undefined"}
```

**Comment by mrlesmithjr** [comment]
This should be resolved now.

**Comment by bunchc** [comment]
Thanks for cleaning that up. Looks good to me.

-C

**Comment by mrlesmithjr** [comment]
Absolutely and thanks! Just did not want to break anything.
