### ISSUE TITLE
Missing Debian dependencies

### ISSUE THREAD

**Issue by makkus** [mrlesmithjr/ansible-netdata#39]
Hi there, just had my Ubuntu 18.04 install fail because of missing dependencies. Comparing the 'official' list (from: https://docs.netdata.cloud/packaging/installer/#linux-64bit-pre-built-static-binary ) with the debian package list in defaults.yml, I found those packages were missing:

- libuv1-dev
- liblz4-dev
- libjudy-dev
- libssl-dev

After installing those manually, the build worked again.

**Comment by mrlesmithjr** [comment]
@makkus Thanks for this. I am way behind on these open issues for sure. I believe that #44 will address a few of these.

**Comment by mrlesmithjr** [comment]
This issue seems to be resolved. Closing this open issue. Please reopen if needed.
