### ISSUE TITLE
Install from static binary

### ISSUE THREAD

**Issue by elcomtik** [mrlesmithjr/ansible-netdata#42]
I found your role very usefull, however i don't like install from source. Netdada ships pre-build static binaries (https://docs.netdata.cloud/packaging/installer/#linux-64bit-pre-built-static-binary)

Would you like PR with changes needed for installing it using pre-build binary?

**Comment by mrlesmithjr** [comment]
@elcomtik Thanks for this info. Glad you found this role useful. And I apologize for the late response to this. I am completely open to this if the collective group of contributors feel it also makes sense. For now I am pinging @gaetanfl @bunchc for their thoughts on this as well.

**Comment by mrlesmithjr** [comment]
Reference for static binaries install is https://docs.netdata.cloud/packaging/installer/methods/kickstart-64/

**Comment by elcomtik** [comment]
maybe https://github.com/mrlesmithjr/ansible-netdata/issues/47 is even more useful
