### ISSUE TITLE
Requirement for lm-sensors fails on EC2 instance

### ISSUE THREAD

**Issue by roens** [mrlesmithjr/ansible-netdata#7]
I'm quite interested in using your (well written) role. However, my environment is entirely within AWS (Ubuntu 16.04 LTS & Amazon Linux), where `lm-sensors` wouldn't seem to apply (is for monitoring hardware, no?).

    TASK [mrlesmithjr.netdata : debian | Installing Pre-Reqs] ***********************************************************************
    task path: /Users/roens/.ansible/roles/mrlesmithjr.netdata/tasks/debian.yml:2
    skipping: [prod-ingest] => (item=[])  => {"changed": false, "item": [], "skip_reason": "Conditional result was False"}
    
    TASK [mrlesmithjr.netdata : redhat | Installing Pre-Reqs] ***********************************************************************
    task path: /Users/roens/.ansible/roles/mrlesmithjr.netdata/tasks/redhat.yml:2
    failed: [prod-ingest] (item=['autoconf', 'automake', 'curl', 'gcc', 'git', 'iproute', 'libmnl-devel', 'libuuid-devel', 'lm_sensors', 'make', 'MySQL-python', 'nc', 'pkgconfig', 'python', 'python-psycopg2', 'PyYAML', 'util-linux', 'uuid', 'uuid-devel', 'zlib-devel']) => {"changed": false, "item": ["autoconf", "automake", "curl", "gcc", "git", "iproute", "libmnl-devel", "libuuid-devel", "lm_sensors", "make", "MySQL-python", "nc", "pkgconfig", "python", "python-psycopg2", "PyYAML", "util-linux", "uuid", "uuid-devel", "zlib-devel"], "msg": "No package matching 'lm_sensors' found available, installed or updated", "rc": 126, "results": ["curl-7.53.1-14.81.amzn1.x86_64 providing curl is already installed", "iproute-4.4.0-3.23.amzn1.x86_64 providing iproute is already installed", "No package matching 'lm_sensors' found available, installed or updated"]}

Is there a good way to exclude that one pre_req for either Linux flavor? Or should I just redefine each `netdata_*_pre_reqs` with equivalent lists, dropping `lm-sensors`?

Thanks!

**Comment by roens** [comment]
I can confirm that stating both `netdata_*_pre_reqs` list (excluding `lm-sensors` from each) in my `include_role` seems to have installed Netdata without issue.

**Comment by mrlesmithjr** [comment]
@roens Awesome. Yes, you should be able to just comment those pre-reqs out as needed.
